export const fakeCities = [
  { id: 1, name: 'Алматы', type: 'courier', price: 1200 },
  { id: 2, name: 'Актобе', type: 'post', price: 800 },
  { id: 3, name: 'Нур-Султан', type: 'pickup', price: 343 },
  { id: 4, name: 'Шымкент', type: 'courier', price: 1100 },
  { id: 5, name: 'Караганда', type: 'post', price: 900 },
  { id: 6, name: 'Тараз', type: 'pickup', price: 3423 },
  { id: 7, name: 'Павлодар', type: 'courier', price: 1000 },
  { id: 8, name: 'Усть-Каменогорск', type: 'post', price: 750 },
  { id: 9, name: 'Семей', type: 'pickup', price: 4440 },
  { id: 10, name: 'Атырау', type: 'courier', price: 1300 },
  { id: 11, name: 'Костанай', type: 'post', price: 850 },
  { id: 12, name: 'Кызылорда', type: 'pickup', price: 444 },
  { id: 13, name: 'Уральск', type: 'courier', price: 1250 },
  { id: 14, name: 'Петропавловск', type: 'post', price: 950 },
  { id: 15, name: 'Темиртау', type: 'pickup', price: 333 },
  { id: 16, name: 'Актау', type: 'courier', price: 1400 },
  { id: 17, name: 'Жезказган', type: 'post', price: 700 },
  { id: 18, name: 'Талдыкорган', type: 'pickup', price: 234 },
  { id: 19, name: 'Кокшетау', type: 'courier', price: 1150 },
  { id: 20, name: 'Рудный', type: 'post', price: 600 }
]
